# Generated by Django 3.0.3 on 2020-03-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_snapshot_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='heading',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='speed_mph',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
