# Generated by Django 2.2.6 on 2019-10-11 03:16

from django.db import migrations

def add_initial_scale(apps, schema_editor):
    SnapshotRatingScale = apps.get_model('records', 'SnapshotRatingScale')
    SnapshotRatingScale.objects.create(names=["Inexcusable", 
                                              "Sucks", 
                                              "Not Great", 
                                              "Fine", 
                                              "Perfect"], values=[1,2,3,4,5])

def remove_initial_scale(apps, schema_editor):
    SnapshotRatingScale = apps.get_model('records', 'SnapshotRatingScale')
    SnapshotRatingScale.objects.all().delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_scale, remove_initial_scale)
    ]
