# Generated by Django 3.0.3 on 2020-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200328_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='photo_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
