# Generated by Django 3.0.3 on 2020-04-07 14:29

from django.db import migrations
from django.conf import settings
from collections import Counter
import boto3

def check_photo_uploaded(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    s3 = boto3.client('s3',
                      aws_access_key_id=settings.AWS_ACCESS_KEY,
                      aws_secret_access_key=settings.AWS_SECRET_KEY)
    objs = s3.list_objects(Bucket=settings.S3_PHOTOS_BUCKET)
    contents = objs['Contents']
    photo_ids = set(c['Key'] for c in contents)
    Snapshot = apps.get_model('records', 'Snapshot')
    counts = Counter()
    width = 488

    for snapshot in Snapshot.objects.all():
        key_name = '%sx/%s.jpg' % (width, snapshot.photo_id)
        snapshot.photo_uploaded = key_name in photo_ids
        counts[snapshot.photo_uploaded] += 1
        snapshot.save()
    
    print(f"\n\t ---> Counts: {counts}\n")

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_snapshot_photo_uploaded'),
    ]

    operations = [
        migrations.RunPython(check_photo_uploaded),
    ]
