# Generated by Django 3.0.3 on 2020-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_snapshot_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='place_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='poi',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
