# Generated by Django 3.0.3 on 2020-04-21 18:23

from django.db import migrations
from django.conf import settings
from mapbox import Geocoder
from pprint import pprint

def fetch_reverse_geocode(apps, schema_editor):
    Snapshot = apps.get_model('records', 'Snapshot')
    geocoder = Geocoder(access_token=settings.MAPBOX_ACCESS_TOKEN)
    
    for snapshot in Snapshot.objects.all():
        # snapshot.fetch_reverse_geocode()
        response = geocoder.reverse(lon=snapshot.location.y, lat=snapshot.location.x, types=["poi"])
        if response.status_code == 200:
            features = response.geojson()['features']
            if len(features) == 0: continue
            pprint(features[0])
            poi = features[0]['text']
            address = features[0]['properties']['address']
            place_name = features[0]['place_name']
            snapshot.poi = poi
            snapshot.address = address
            snapshot.place_name = place_name
            snapshot.save()
            print(f"\n\t ---> Snapshot: {snapshot.poi} — {snapshot.address} \n")
        else:
            print(f"\n\t ---> ERROR Snapshot: {response} {snapshot}\n")
            


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_geocode'),
    ]

    operations = [
        migrations.RunPython(fetch_reverse_geocode, migrations.RunPython.noop),
    ]
