# Generated by Django 3.0.3 on 2020-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_reverse_geocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='email_hash',
            field=models.CharField(default='xxx', max_length=64),
            preserve_default=False,
        ),
    ]
