# Generated by Django 3.0.3 on 2020-04-22 14:45

from django.conf import settings
from django.db import migrations
import hashlib
from collections import Counter

def calcluate_hashes(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Snapshot = apps.get_model('records', 'Snapshot')
    counts = Counter()
    
    for snapshot in Snapshot.objects.all():
        counts[snapshot.user.email] += 1
        snapshot.email_hash = hashlib.md5(snapshot.user.email.encode('utf-8')).hexdigest()
        snapshot.save()
    
    print(f"\n ---> Migrated {Snapshot.objects.all().count()} snapshots with {counts}")
    
class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_snapshot_email_hash'),
    ]

    operations = [
        migrations.RunPython(calcluate_hashes, migrations.RunPython.noop),
    ]
