---
- name: Clone App Repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dir }}"
    accept_hostkey: yes
    key_file: /srv/comfortmaps-secrets/keys/comfortmaps-web.pem
    update: yes

- name: Reloading app server (systemd)
  become: yes
  systemd:
    name: gunicorn
    state: reloaded



