# Generated by Django 2.2.6 on 2019-10-11 03:16

from django.db import migrations


def add_initial_scale(apps, schema_editor):
    SnapshotRatingScale = apps.get_model('record', 'SnapshotRatingScale')
    SnapshotRatingScale.objects.create(names=["Inexcusable", 
                                              "Sucks", 
                                              "Not Great", 
                                              "Fine", 
                                              "Perfect"], values=[1,2,3,4,5])
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_scale)
    ]
