---
- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: installed 
    update_cache: yes
  with_items:
    - curl
    - git
    - zsh

- name: "Set MOTD banner"
  become: yes
  template:
    src: "motd.txt"
    dest: "/etc/update-motd.d/80-weel-motd"
    mode: 0755

- name: Adding ssh config for comfortmaps
  blockinfile:
    dest: ~/.ssh/config
    create: yes
    marker: "## {mark} added for comfortmaps"
    block: |
      Host comfortmaps.github.com
      HostName github.com
      User git
      IdentityFile ~/.ssh/comfortmaps-web.pem

- name: Add comfortmaps-web.pem.pub
  template:
    src: /srv/comfortmaps-secrets/keys/comfortmaps-web.pem.pub
    dest: ~/.ssh/comfortmaps-web.pem.pub
    mode: 0600

- name: Add comfortmaps-web.pem
  template:
    src: /srv/comfortmaps-secrets/keys/comfortmaps-web.pem
    dest: ~/.ssh/comfortmaps-web.pem
    mode: 0600
    