# Generated by Django 2.2.6 on 2020-02-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='missing', max_length=254, unique=True, verbose_name='Email address'),
            preserve_default=False,
        ),
    ]
